
CREATE TABLE student
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(50)                             NOT NULL,
    last_name  VARCHAR(50)                             NOT NULL,
    email      VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_student PRIMARY KEY (id)
);